/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EnBlockAppendModeSelector: typeof import('./src/components/EnBlockAppendModeSelector.vue')['default']
    EnBlockJumper: typeof import('./src/components/EnBlockJumper.vue')['default']
    EnButtonIcon: typeof import('./src/components/EnButtonIcon.vue')['default']
    EnColorPicker: typeof import('./src/components/EnColorPicker.vue')['default']
    EnDivider: typeof import('./src/components/EnDivider.vue')['default']
    EnDock: typeof import('./src/components/EnDock/EnDock.vue')['default']
    EnDrawer: typeof import('./src/components/EnDrawer.vue')['default']
    EnIconDragon: typeof import('./src/components/EnIconDragon.vue')['default']
    EnIconLeaf: typeof import('./src/components/EnIconLeaf.vue')['default']
    EnIconLeaf2: typeof import('./src/components/EnIconLeaf2.vue')['default']
    EnIconTarget: typeof import('./src/components/EnIconTarget.vue')['default']
    EnModal: typeof import('./src/components/EnModal.vue')['default']
    EnNotebookSelector: typeof import('./src/components/EnNotebookSelector.vue')['default']
    EnProtyle: typeof import('./src/components/EnProtyle.vue')['default']
    EnProtyleAuto: typeof import('./src/components/EnProtyleAuto.vue')['default']
    EnProtyleAutoRender: typeof import('./src/components/EnProtyleAutoRender.vue')['default']
    EnProtyleCustomArea: typeof import('./src/components/EnProtyleCustomArea.vue')['default']
    EnSyEmoji: typeof import('./src/components/EnSyEmoji.vue')['default']
    EnTagsContainer: typeof import('./src/components/EnTagsContainer.vue')['default']
    EnUsageLink: typeof import('./src/components/EnUsageLink.vue')['default']
    FixedDocArea: typeof import('./src/components/FixedDocArea.vue')['default']
    SyButton: typeof import('./src/components/SiyuanTheme/SyButton.vue')['default']
    SyCheckbox: typeof import('./src/components/SiyuanTheme/SyCheckbox.vue')['default']
    SyIcon: typeof import('./src/components/SiyuanTheme/SyIcon.vue')['default']
    SyInput: typeof import('./src/components/SiyuanTheme/SyInput.vue')['default']
    SySelect: typeof import('./src/components/SiyuanTheme/SySelect.vue')['default']
    SyTextarea: typeof import('./src/components/SiyuanTheme/SyTextarea.vue')['default']
  }
}
