/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EnBlockAppendModeSelector: typeof import('./../components/EnBlockAppendModeSelector.vue')['default']
    EnBlockJumper: typeof import('./../components/EnBlockJumper.vue')['default']
    EnButtonIcon: typeof import('./../components/EnButtonIcon.vue')['default']
    EnColorPicker: typeof import('./../components/EnColorPicker.vue')['default']
    EnDivider: typeof import('./../components/EnDivider.vue')['default']
    EnDock: typeof import('./../components/EnDock/EnDock.vue')['default']
    EnDrawer: typeof import('./../components/EnDrawer.vue')['default']
    EnIconDragon: typeof import('./../components/EnIconDragon.vue')['default']
    EnIconExpand: typeof import('./../components/EnIconExpand.vue')['default']
    EnIconLeaf: typeof import('./../components/EnIconLeaf.vue')['default']
    EnIconLeaf2: typeof import('./../components/EnIconLeaf2.vue')['default']
    EnIconTarget: typeof import('./../components/EnIconTarget.vue')['default']
    EnModal: typeof import('./../components/EnModal.vue')['default']
    EnNotebookSelector: typeof import('./../components/EnNotebookSelector.vue')['default']
    EnProtyle: typeof import('./../components/EnProtyle.vue')['default']
    EnProtyleAuto: typeof import('./../components/EnProtyleAuto.vue')['default']
    EnProtyleAutoRender: typeof import('./../components/EnProtyleAutoRender.vue')['default']
    EnProtyleCustomArea: typeof import('./../components/EnProtyleCustomArea.vue')['default']
    EnSyEmoji: typeof import('./../components/EnSyEmoji.vue')['default']
    EnSyTab: typeof import('./../components/EnSyTab.vue')['default']
    EnTagsContainer: typeof import('./../components/EnTagsContainer.vue')['default']
    EnUsageLink: typeof import('./../components/EnUsageLink.vue')['default']
    FixedDocArea: typeof import('./../components/FixedDocArea.vue')['default']
    SyButton: typeof import('./../components/SiyuanTheme/SyButton.vue')['default']
    SyCheckbox: typeof import('./../components/SiyuanTheme/SyCheckbox.vue')['default']
    SyIcon: typeof import('./../components/SiyuanTheme/SyIcon.vue')['default']
    SyInput: typeof import('./../components/SiyuanTheme/SyInput.vue')['default']
    SySelect: typeof import('./../components/SiyuanTheme/SySelect.vue')['default']
    SyTextarea: typeof import('./../components/SiyuanTheme/SyTextarea.vue')['default']
  }
}
