/* eslint-disable perfectionist/sort-enums */
export enum EN_CONSTANTS {
  AUTH = 'EnSettingsAuth',



  // 全局数据
  GLOBAL_DATA = 'GlobalData',
  // 全局模块
  GLOBAL_MODULE = 'GlobalModule',
  // 窗口的全局数据
  GLOBAL_WINDOW_DATA = 'GlobalWindowData',


  EN_PLUGIN_SWITCH = 'En_Plugin_Switch',
  EN_PLUGIN_SWITCH_DISPLAY = '开/关插件',



  BACKGROUND_IMG = 'EnBackgroundImg',
  BACKGROUND_IMG_DISPLAY = '背景图',


  EN_BOTTOM_BACKLINK = 'EnBottomBacklink',
  EN_BOTTOM_BACKLINK_DISPLAY = '底部反链',


  COMMENT = 'EnComment',
  COMMENT_DISPLAY = '批注',


  CMD_KEY_EN_OPEN_QUICK_NOTE = 'En_OpenQuickNote',



  DAILY_NOTE = 'DailyNote',
  DAILY_NOTE_DISPLAY = '日记',


  EN_FORMAT_BRUSH = 'EnFormatBrush',
  EN_FORMAT_BRUSH_DISPLAY = '格式刷',


  EN_OTHER = 'EnOther',
  EN_OTHER_DISPLAY = '其他设置',
  EN_OTHER_LINK_COLOR = 'EnOtherLinkColor',
  EN_OTHER_BLOCK_REF_BRACKET = 'EnOtherBlockRefBracket',
  EN_OTHER_IMAGE_DEFAULT_WIDTH = 'EnOtherImageDefaultWidth',
  EN_OTHER_DAILY_NOTE_FIRST_BLOCK_BG = 'EnOtherDailyNoteFirstBlockBg',

  EN_PARAGRAPH_BLOCK = 'EnParagraphBlock',
  EN_PARAGRAPH_BLOCK_DISPLAY = '段落块相关',

  EN_SERVER = 'EnServer',
  EN_SERVER_DISPLAY = 'API 服务',



  EN_TEST_LOGIC = 'TestLogic',


  FONT_STYLE = 'EnFont',
  FONT_STYLE_DISPLAY = '字体样式快捷键',


  LIFELOG = 'EnLifeLog',
  LIFELOG_DISPLAY = 'LifeLog',


  EN_VIDEO_AND_AUDIO = 'EnVideoAndAudio',
  EN_VIDEO_AND_AUDIO_DISPLAY = '音视频',


  WHITEBOARD_BASE_PATH = 'EnWhiteBoard',
  EN_WHITE_BOARD = `${WHITEBOARD_BASE_PATH}/config`,
  EN_WHITE_BOARD_DISPLAY = '白板',
  EN_WHITE_BOARD_INDEX_MAP = `${WHITEBOARD_BASE_PATH}/IndexMap`,
  EN_WHITE_BOARD_WHITEBOARD_LIST = `${WHITEBOARD_BASE_PATH}/WhiteboardList`,

  EN_WHITE_BOARD_NODE_TYPE_PROTYLE = 'EnWhiteBoardNodeProtyle',

  EN_WHITE_BOARD_EDGE_TYPE_BASE = 'EnWhiteBoardEdgeBase',

  EN_WHITE_BOARD_HANDLE_PLACEHOLDER = 'EnWhiteBoardHandlePlaceholder',



  MODULE_PROVIDER_KEY = 'EnModule',



  NOTEBOOK_LIST_OPENED = 'NOTEBOOK_LIST_OPENED',
  NOTEBOOK_LIST_OPENED_UPDATOR = 'NOTEBOOK_LIST_OPENED_UPDATOR',



  PARAGRAPH_BLOCK_TIME_DIFF = 'EnParagraphBlockTimeDiff',


  PWA = 'EnPWA',
  PWA_DISPLAY = '移动端 PWA 适配',

  QUICK_NOTE = 'QuickNote',
  QUICK_NOTE_DISPLAY = '一键记事',



  SETTINGS = 'EnSettings',
  SETTINGS_ITEM_MODE_HORIZONTAL = 'horizontal',
  SETTINGS_ITEM_MODE_VERTICAL = 'vertical',



  EN_TEMPLATES = 'EnTemplates',
  EN_TEMPLATES_DISPLAY = '模板',
}

export enum EN_COMMAND_KEYS {
  EN_PLUGIN_SWITCH = EN_CONSTANTS.EN_PLUGIN_SWITCH,

  EN_OPEN_QUICK_NOTE = EN_CONSTANTS.CMD_KEY_EN_OPEN_QUICK_NOTE,
}

export enum EN_MODULE_LIST {
  SETTINGS = EN_CONSTANTS.SETTINGS,
  AUTH = EN_CONSTANTS.AUTH,

  EN_TEST_LOGIC = EN_CONSTANTS.EN_TEST_LOGIC,

  BACKGROUND_IMG = EN_CONSTANTS.BACKGROUND_IMG,

  EN_BOTTOM_BACKLINK = EN_CONSTANTS.EN_BOTTOM_BACKLINK,

  COMMENT = EN_CONSTANTS.COMMENT,

  DAILY_NOTE = EN_CONSTANTS.DAILY_NOTE,

  EN_FORMAT_BRUSH = EN_CONSTANTS.EN_FORMAT_BRUSH,

  EN_OTHER = EN_CONSTANTS.EN_OTHER,

  EN_PARAGRAPH_BLOCK = EN_CONSTANTS.EN_PARAGRAPH_BLOCK,

  EN_VIDEO_AND_AUDIO = EN_CONSTANTS.EN_VIDEO_AND_AUDIO,

  FONT_STYLE = EN_CONSTANTS.FONT_STYLE,

  LIFELOG = EN_CONSTANTS.LIFELOG,

  PWA = EN_CONSTANTS.PWA,

  QUICK_NOTE = EN_CONSTANTS.QUICK_NOTE,

  EN_SERVER = EN_CONSTANTS.EN_SERVER,

  EN_TEMPLATES = EN_CONSTANTS.EN_TEMPLATES,

  EN_WHITE_BOARD = EN_CONSTANTS.EN_WHITE_BOARD,
}

export enum EN_EVENT_BUS_KEYS {
  SETTINGS_OPEN_ON_ENTRY = 'settings:openOnEntry',
  AUTH_OPEN_MODAL = 'auth:openModal',
  CREATE_TODAY_DAILY_NOTE_MOBILE = 'createTodayDailyNote_mobile',
  LIFELOG_LOAD_RECORDS_BY_DATE_LIST = 'LIFELOG_LOAD_RECORDS_BY_DATE_LIST',
  MEMO_FOCUS_INPUT = 'memo:focusInput',
}


export enum EN_STYLE_KEYS {
  enTimeFontSize = '--enTimeFontSize',
  enAttrContainerWidth = '--enAttrContainerWidth',
  enBottomBacklinkTopDistance = '--enBottomBacklinkTopDistance',
}

/**
 * 全局管理 provide 的 key，防止在不同的地方编写出现重复的 key
 */
export enum EN_PROVIDE_KEYS {
  EN_COMMENT_OPTIONS = 'EN_COMMENT_OPTIONS',
  EN_COMMENT_ID_LIST = 'EN_COMMENT_ID_LIST',
}
